### PR TITLE
Added OSX and Linux builders to .travis.yml

### LINKED ISSUE #65: Add a CI builder for MacOSX
I know that TravisCI has MacOSX support, but I did not look into that yet.

### PR DESCRIPTION
**Pull request by maksimov**
Fixes #65

### CODE REVIEW

**Comment by maksimov** [comment]
Welcome to the land of slower builds!

**Comment by zimmski** [comment]
Awesome! https://travis-ci.org/sergi/go-diff/jobs/180966792 looks good to me. The error at the bottom can be ignored according to https://github.com/travis-ci/travis-ci/issues/6307

**Comment by zimmski** [comment]
Amazing how simple that was. Thank you very much :tada:

**Comment by maksimov** [comment]
Thanks for looking after my PRs on a Saturday ;-)

**Pull request merged**
