### PR TITLE
Drop Apache-2.0 licensing claim

### PR DESCRIPTION
**Pull request by MTecknology**
[hm... dropping this because I need to research a bit more... sorry!]

### CODE REVIEW

**Comment by zimmski** [comment]
@MTecknology AFAIK the Apache licence allows you to choose to release your modified version under a different license but you are required to retain the Apache License for the unmodified parts of the code. Since everything has been rewritten (into another language) the MIT licence alone should be fine for everything in the repository, and we can drop the Apache licence. However, these things are tricky and I think that it would be wise to ask someone who mumbles licences in his sleep. Since you are doing official (?) Debian packages: Can you ping somebody of the Debian project?

FYI I am not the original author of the original implementation and I am not the author of the rewrite, I just did a lot of other rewrites of this repository and added/modified some things here and there, and currently I help maintain this repository.

**Comment by MTecknology** [comment]
Sorry... I found the answers and forgot to follow up.

You're correct; the re-license was perfectly acceptable. The Apache license /can/ be dropped from the repository because it is not being applied to any files within the repository. In fact, this was the cause to my initial confusion. I had absolutely no clue how to mark missing files with the license.

This is the copyright file I came up with that meets Debian guidelines and retains attributions. (You handled the same in README.md.)
https://anonscm.debian.org/cgit/pkg-go/packages/golang-github-sergi-go-diff.git/tree/debian/copyright

**Comment by zimmski** [comment]
@MTecknology Alright, I will ping the author of this repository if he is OK with this change. I cannot repopen this PR since the branch has been deleted. Do you want to reupload your branch, or should I create a new one?

**Comment by MTecknology** [comment]
Sorry, this dropped off my radar since it was closed and this package is now included in Debian. I just ignored it's presence.

My only changes to the repository were removing the file and this diff. http://dpaste.com/2XG3KZH

If you're curious, this is the d/copyright file that was produced for this project:
    https://anonscm.debian.org/cgit/pkg-go/packages/golang-github-sergi-go-diff.git/tree/debian/copyright

**Pull request closed without merging**
